apiVersion: v1
kind: Service
metadata:
  name: booklist-service
spec:
  type: NodePort
  selector:
    app: booklist
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
      nodePort: 31234
